image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - ps: sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - ps: sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose up -d
  - sleep 30
  - java -jar ./artifacts/aqa-shop.jar &
  - sleep 30
build_script:
  - ./gradlew test -Dselenide.headless=true --info
 
  
